Linear split test
lambdaclass/cairo-rs pull request #1118
Opened 2023-05-05 14:58 UTC by mmsc2

# TITLE

## Description

Description of the pull request changes and motivation.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

2023-05-09 14:38 UTC, pefontana requested changes

2023-05-09 14:38 UTC, pefontana commented on cairo_programs/cairo-1-contracts/linear_split.cairo
> +}
add end line

2023-05-09 14:38 UTC, pefontana commented on src/tests/cairo_1_hints.rs
move this test to `src/tests/cairo_1_run_from_entrypoint_tests.rs` and remove this file

2023-05-09 21:29 UTC, pefontana commented on CHANGELOG.md
> +* Implement test for LinearSplit hint [#1118](https://github.com/lambdaclass/cairo-rs/pull/1118)
I think it is not necesery to update the changelog
Since we are just adding tests

2023-05-10 18:13 UTC, pefontana approved these changes

2023-05-10 18:27 UTC, juanbono approved these changes

2023-05-10 19:21 UTC, merged