Alloc felt dict test
lambdaclass/cairo-rs pull request #1125
Opened 2023-05-05 18:26 UTC by mmsc2

# TITLE

## Description

Description of the pull request changes and motivation.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

2023-05-08 13:37 UTC, fmoletta commented on .gitignore
> +**/*.casm
Please add line

2023-05-08 13:38 UTC, fmoletta commented on cairo_programs/cairo-1-contracts/felt_252_dict.cairo
> +}
Please add line

2023-05-10 21:17 UTC, pefontana requested changes

2023-05-10 21:17 UTC, pefontana commented on src/tests/cairo_1_hints.rs
move this to src/tests/cairo_1_run_from_entrypoint_tests.rs

2023-05-11 15:53 UTC, fmoletta commented on cairo_programs/cairo-1-contracts/felt_252_dict.cairo
> +    fn segment_arena_builtin() -> bool {
This name doesn't reflect what the func does, maybe it could be called `squash_dict` or `squash_empty_dict`

2023-05-11 19:04 UTC, fmoletta commented
Please remove the cairo submodule. This should also fix CI

2023-05-12 18:54 UTC, Oppen approved these changes

2023-05-12 19:10 UTC, fmoletta approved these changes

2023-05-12 21:07 UTC, pefontana approved these changes

2023-05-12 21:10 UTC, juanbono approved these changes

2023-05-12 21:10 UTC, juanbono approved these changes

2023-05-12 21:42 UTC, merged