Make a Cairo 1 program for testing ShouldSkipSquashLoop hint
lambdaclass/cairo-rs pull request #1149
Opened 2023-05-09 15:32 UTC by rcatalan98

# Make a Cairo 1 program for testing ShouldSkipSquashLoop hint

## Description

Description of the pull request changes and motivation.

## Checklist
- [x] Linked to Github Issue
- [x] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

Closes #1116

2023-05-10 17:56 UTC, pefontana requested changes

2023-05-10 17:56 UTC, pefontana commented on cairo_programs/cairo-1-contracts/should_skip_squash_loop.cairo
> +}
add endline

2023-05-10 17:56 UTC, pefontana commented on CHANGELOG.md
> +* Add a test for the `ShouldSkipSquashLoop` hint [#1149](https://github.com/lambdaclass/cairo-rs/pull/1149).
since we are only adding test we dont need to add nothing to the changelog

2023-05-10 17:56 UTC, pefontana commented on cairo_programs/cairo-1-contracts/should_skip_squash_loop.cairo
> +}
Maybe i am wrong here, but can we return `x.squash()` so we can check it in the test

2023-05-11 16:28 UTC, pefontana approved these changes

2023-05-11 16:33 UTC, fmoletta approved these changes

2023-05-11 16:39 UTC, Oppen approved these changes

2023-05-11 17:40 UTC, merged