Add cairo program for testing AllocSegment hint
lambdaclass/cairo-rs pull request #1156
Opened 2023-05-10 20:19 UTC by mfachal

# Test AllocSegment hint

## Description

Add cairo 1.0 program for testing AllocSegment casm hint.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

2023-05-10 21:11 UTC, fmoletta commented on CHANGELOG.md
> +
Please remove this. Tests are not relevant in the changelog

2023-05-10 21:23 UTC, pefontana requested changes

2023-05-10 21:23 UTC, pefontana commented on .gitignore
> +cairo_programs/cairo-1-contracts/*.sierra
restore this file, it is already added in 
```
**/*.casm
**/*.sierra
```

2023-05-11 06:10 UTC, Oppen approved these changes

2023-05-11 16:22 UTC, merged