Add unit tests to hints
lambdaclass/cairo-rs pull request #433
Opened 2022-09-20 20:26 UTC by Juan-M-V

# Extend unit tests

## Description

Add some unit tests to the hints module to increase overage

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2022-10-12 22:59 UTC, fmoletta commented on src/hint_processor/hint_processor_utils.rs
> +}
Use VirtualMachine.get_range_check_builtin() instead

2022-10-19 13:32 UTC, Juan-M-V commented on src/hint_processor/hint_processor_utils.rs
> +}
Resolved https://github.com/lambdaclass/cairo-rs/pull/433/commits/6374618143e0d363d5f97309bc8e1e400a2252fd

2022-11-02 21:42 UTC, fmoletta approved these changes

2022-11-02 21:47 UTC, pefontana requested changes
Nice one @Juan-M-V !
I made a git merge main locally and some test start failling. 
Can you merge main and update them, so we can merge them

2022-11-07 14:22 UTC, pefontana approved these changes

2022-11-07 14:23 UTC, merged