Refactor Memory methods to handle Temporary segment cases
lambdaclass/cairo-rs pull request #482
Opened 2022-10-14 20:32 UTC by pefontana

# Refactor Memory methods to handle Temporary segment cases

* Refactor `Memory.get` method to get values from Temporary Segments
* Refactor `Memory.insert` method to insert values in Temporary Segments
* Refactor fn `from_relocatable_to_indexes`
* Add `Memory.relocation_rules` field

## Checklist
- [ ] Linked to Github Issue
- [x] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2022-10-19 13:07 UTC, Juan-M-V commented on src/types/relocatable.rs
>              }
`ok_or(MemoryError::Relocation)` can be used instead of this match block

2022-10-19 20:40 UTC, Oppen requested changes

2022-10-19 20:40 UTC, Oppen commented on src/hint_processor/builtin_hint_processor/dict_manager.rs
> +        };
Need a test for this case.

2022-10-19 20:40 UTC, Oppen commented on src/vm/trace/trace_entry.rs
> +    })?;
Missing test.

2022-10-19 20:40 UTC, Oppen commented on src/vm/vm_core.rs
> +            })?;
Missing test.

2022-10-19 20:40 UTC, Oppen commented on src/vm/vm_memory/memory.rs
> +        let (i, j) = from_relocatable_to_indexes(&relocatable);
Is `from_relocatable_to_indexes` fixing the negative index? It should be something like `-(segment_index+1)`.

2022-10-20 23:03 UTC, Oppen approved these changes

2022-10-21 12:54 UTC, merged