feat: enable the skip_instruction_exectution for hints
lambdaclass/cairo-rs pull request #518
Opened 2022-10-28 18:21 UTC by tdelabro

the feature making hints able to disable next instruction executions was disabled

2022-10-28 18:28 UTC, fmoletta approved these changes
Thanks for the PR! Its definitely a needed feature

2022-10-28 18:45 UTC, HermanObst requested changes
Hi @tdelabro thanks for adding this feature! 
Please add a small integration test with a hint that uses this method and check correct functionality.
If you need help with this just let me know

2022-11-01 11:40 UTC, tdelabro commented
> Hi @tdelabro thanks for adding this feature! Please add a small integration test with a hint that uses this method and check correct functionality. If you need help with this just let me know

Sure. Where do you want this test to appear ? In `vm_core.rs`, or you want a full `.cairo` file with a `%{ skip_next_instruction %}` hint and run on a custom HintExecutor  ?

Also can you fix #533  so I can develop my own test without noise

2022-11-30 21:55 UTC, Eikix commented
hey y'all @fmoletta & @HermanObst :)! I'm Elias, I'll be helping @tdelabro on this issue / cairo-foundry. Could you provide additional information for writing the integration test?
-  since it requires a `.cairo` file, a hint and a `cairo-run` call, what is the correct place for this test to live?

2022-12-07 10:24 UTC, tdelabro commented
@Eikix usually they live there: https://github.com/lambdaclass/cairo-rs/tree/main/cairo_programs
So you can create one there and make it use a custom `skip_next_instruction` hint.
Then you create your test where you use a hintProcessor that has access to an implem of this hint in order to execute the said cairo.program

2022-12-08 16:20 UTC, Eikix commented
I opened #645 as a replacement PR for this one

2022-12-09 09:02 UTC, closed without merging

2022-12-09 09:02 UTC, tdelabro commented
replaced by #645