Get range method
lambdaclass/cairo-rs pull request #529
Opened 2022-10-31 19:50 UTC by mmsc2

2022-10-31 19:59 UTC, fmoletta requested changes
Please add tests for both methods

2022-11-01 12:05 UTC, Juan-M-V commented on src/vm/vm_core.rs
> +        self.memory.get_continuos_range(addr, size)
it should be continuous instead

2022-11-01 15:29 UTC, mmsc2 commented on src/vm/vm_core.rs
> +        self.memory.get_continuos_range(addr, size)
fixed

2022-11-01 15:34 UTC, fmoletta commented on src/vm/vm_memory/memory.rs
> +        let mut values = Vec::new();
```suggestion
        let mut values = Vec::with_capacity(size);
```

2022-11-01 18:37 UTC, mmsc2 commented on src/vm/vm_memory/memory.rs
> +        let mut values = Vec::new();
Targeted

2022-11-02 14:35 UTC, mmsc2 commented on src/vm/errors/memory_errors.rs
> +    #[error("Found a memory gap when calling get_continous_range")]
fixed

2022-11-02 15:23 UTC, fmoletta commented on src/vm/vm_memory/memory.rs
> +    fn getcontinuous_range_for_continuous_memory() {
```suggestion
    fn get_continuous_range_for_continuous_memory() {
```

2022-11-02 15:33 UTC, fmoletta approved these changes
Great Work!

2022-11-02 17:43 UTC, merged