Expose get_segment_used_size
lambdaclass/cairo-rs pull request #545
Opened 2022-11-02 20:46 UTC by mmsc2

2022-11-02 21:16 UTC, fmoletta requested changes

2022-11-02 21:16 UTC, fmoletta commented on src/vm/vm_core.rs
> +        assert_eq!(Some(8), vm.segments.get_segment_used_size(2));
```suggestion
        assert_eq!(Some(8), vm.get_segment_used_size(2));
```
The new method is not being tested

2022-11-02 21:16 UTC, fmoletta commented on src/vm/vm_core.rs
> +        assert_eq!(None, vm.segments.get_segment_used_size(2));
```suggestion
        assert_eq!(None, vm.get_segment_used_size(2));
```
Same here

2022-11-03 14:28 UTC, mmsc2 commented on src/vm/vm_core.rs
> +        assert_eq!(Some(8), vm.segments.get_segment_used_size(2));
Fixed

2022-11-03 14:37 UTC, juanbono approved these changes

2022-11-03 15:25 UTC, fmoletta approved these changes
lgtm

2022-11-03 15:25 UTC, merged