Initialize segments of every builtin and add included field
lambdaclass/cairo-rs pull request #546
Opened 2022-11-02 21:17 UTC by Jrigada

# Initialize segments of every builtin and add included field

## Description

Description of the pull request changes and motivation.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2022-11-02 21:37 UTC, fmoletta requested changes

2022-11-02 21:37 UTC, fmoletta commented on src/vm/runners/cairo_runner.rs
> +        ));
```suggestion
        builtin_runners.push((
            "output".to_string(),
            OutputBuiltinRunner::new(self.program.builtins.contains(&"output".to_string())).into(),
        ));
```

2022-11-02 21:37 UTC, fmoletta commented on src/vm/runners/cairo_runner.rs
> +                difference.contains(&"pedersen".to_string()),
```suggestion
                self.program.builtins.contains(&"pedersen".to_string()),
```

2022-11-02 21:37 UTC, fmoletta commented on src/vm/runners/cairo_runner.rs
> +                    difference.contains(&"range_check".to_string()),
```suggestion
                    self.program.builtins.contains(&"range_check".to_string()),
```

2022-11-02 21:37 UTC, fmoletta commented on src/vm/runners/cairo_runner.rs
> +                difference.contains(&"bitwise".to_string()),
```suggestion
                self.program.builtins.contains(&"bitwise".to_string()),
```

2022-11-02 21:37 UTC, fmoletta commented on src/vm/runners/cairo_runner.rs
> +                difference.contains(&"ec_op".to_string()),
```suggestion
                self.program.builtinscontains(&"ec_op".to_string()),
```

2022-11-03 14:19 UTC, Oppen commented
Why do `InstanceDef`s become `Option<_>`? What's the use of `included`?

2022-11-03 15:03 UTC, Oppen requested changes

2022-11-03 19:57 UTC, Jrigada commented on src/vm/runners/builtin_runner/bitwise.rs
> +    bitwise_builtin: Option<BitwiseInstanceDef>,
I am still trying to grasp this idea. I do not understand it that well, it seems to me that I would still have a lot of Results due to the checks of the ZeroDivisionErrors. We would need to look into where we need to use this instance def with none values.

2022-11-04 15:08 UTC, fmoletta commented on docs/hint_processor/builtin_hint_processor/README.md
> -    println!("{}", a);
Why did you remove this line?

2022-11-04 15:09 UTC, fmoletta commented on src/vm/runners/builtin_runner/bitwise.rs
> +    ) -> Result<usize, RunnerError> {
Remove this result

2022-11-04 15:13 UTC, fmoletta commented on src/vm/runners/builtin_runner/mod.rs
> +    ) -> Result<usize, RunnerError> {
Remove this result too

2022-11-04 15:13 UTC, Juan-M-V approved these changes
lgtm

2022-11-04 15:20 UTC, fmoletta approved these changes

2022-11-04 15:29 UTC, juanbono approved these changes
LGTM ser!

2022-11-04 17:13 UTC, Oppen approved these changes

2022-11-04 17:13 UTC, merged