Update to cairo 0.10.0
lambdaclass/cairo-rs pull request #626
Opened 2022-11-22 15:17 UTC by Juan-M-V

# TITLE

## Description

Update cairo version to 0.10.0
Resolves: #620 #417 

## Checklist
- [x] Linked to Github Issue
- [x] Unit tests added

2022-11-22 20:36 UTC, Oppen approved these changes

2022-11-23 13:02 UTC, Jrigada approved these changes

2022-11-23 13:56 UTC, fmoletta requested changes
We should wait until integration testing is complete before updating to 0.10

2022-11-28 17:58 UTC, fmoletta approved these changes

2022-11-28 18:27 UTC, mmsc2 approved these changes

2022-12-04 15:22 UTC, unbalancedparentheses commented
Please test it and merge it @Juan-M-V

2022-12-12 19:46 UTC, merged