Update readme with instructions to use cairo-rs directly
lambdaclass/cairo-rs pull request #629
Opened 2022-11-23 19:46 UTC by Jrigada

# Update readme with instructions to use cairo-rs directly

## Description

Description of the pull request changes and motivation.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2022-11-23 19:57 UTC, SantiagoPittella approved these changes

2022-11-24 13:33 UTC, fmoletta requested changes

2022-11-24 13:33 UTC, fmoletta commented on README.md
> +## Running a Cairo Program with Cairo-rs
Isn't this wrong? These are not instructions to run a Cairo program, but to run a function in  a Cairo program while passing its arguments

2022-11-25 15:13 UTC, fmoletta approved these changes

2022-11-28 12:56 UTC, Juan-M-V approved these changes

2022-11-30 14:58 UTC, juanbono approved these changes

2022-12-01 11:34 UTC, SantiagoPittella approved these changes

2022-12-01 13:42 UTC, merged